name: Build and Deploy to K3s on local RasPi

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: gitea.homelab.leuchtstark.dev
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gitea.homelab.leuchtstark.dev/marco/learn-kubernetes:main

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.30.0"

      - name: Deploy to K3s
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl apply -f k8s/ --insecure-skip-tls-verify=true
          kubectl rollout restart deployment learn-kubernetes -n learn-kubernetes
