apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: learn-kubernetes
  name: learn-volume-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/k3s/learn-volume-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: learn-kubernetes
  name: learn-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
