name: Mirror-Code-QA - Public Check Marks

on:
  push:
    branches: ["main"]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt
      - name: install python dependencies
        run: pip install tox
      - name: run TOX 
        run: tox
